spring:
  cloud:
    gateway:
      routes:
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

        - id: yahoo_route
          uri: https://www.yahoo.com
          predicates:
            - Query=url,yahoo